
#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaulZone: http://localhost:9000/eureka

#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${random.uuid}

#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: http://localhost:${server.port}/eureka/
      
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
    fetch-registry: true
    register-with-eureka: true
    
server:
  port: 8081

spring:
  application:
    name: product-catalog